services:
  db:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file: .env.db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file: .env.pgadmin
    ports:
      - "8080:80"
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file: ./api/.env.api
    ports:
    - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
